### ISSUE TITLE
Selectors that use escaped colons like `.md\:focus-within\:bg-red:focus-within` are transformed incorrectly

### ISSUE THREAD

**Issue by adamwathan** [jonathantneal/postcss-focus-within#3]
Hey Jonathan thanks as always for your amazing work in the PostCSS ecosystem!

Today a Tailwind user ran into an issue where classes like this:

```css
.md\:focus-within\:bg-red:focus-within {
  background-color: red;
}
```

...were being incorrectly transformed to this when duplicated for the polyfill:

```css
.md\[focus-within]\:bg-red:focus-within {
  background-color: red;
}
```

I think this is basically the same issue as on `postcss-selector-not` a while back, where the matching is just not considering the fact that the colon might be escaped:

https://github.com/postcss/postcss-selector-not/pull/11

If you'd like I can try and port over a similar fix from that project some time in the next couple of days 👍  I suspect this issue is likely present in the `postcss-focus-visible` plugin as well.

Thanks again!
